// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface IJobBoard {
    function create(string memory title, string memory description, address token, uint quantity, uint duration) external;
    function updateDescription(uint jobId, string memory description) external;
    function updateDuration(uint jobId, uint duration) external;
    function transfer(uint jobId, address manager) external;
    function manage(uint jobId) external;
    function fund(uint jobId, uint quantity) external;
    function apply_(uint jobId) external;
    function unapply(uint jobId) external;
    function offer(uint jobId, bytes32 hash) external;
    function rescind(uint jobId) external;
    function cancel(uint jobId) external;
    function accept(uint jobId, string memory secret) external;
    function end(uint jobId) external;
    function refund(uint jobId, address user) external returns (uint);
    function claim(uint jobId, address to) external;
    function getStatus(uint jobId) external view returns (uint);
    function getTimeAndMoneyOwed(uint jobId) external view returns (uint, uint);
    function getTimeWorked(uint jobId) external view returns (uint);
    function getTitle(uint jobId) external view returns (string memory);
    function getDescription(uint jobId) external view returns (string memory);
    function getManager(uint jobId) external view returns (address);
    function getToken(uint jobId) external view returns (address);
    function getQuantity(uint jobId) external view returns (uint);
    function getDuration(uint jobId) external view returns (uint);
    function getCreateTime(uint jobId) external view returns (uint);
    function getPendingManager(uint jobId) external view returns (address);
    function getPendingOffer(uint jobId) external view returns (bytes32);
    function getWorker(uint jobId) external view returns (address);
    function getStartTime(uint jobId) external view returns (uint);
    function getTimePaid(uint jobId) external view returns (uint);
    function getTimeRefunded(uint jobId) external view returns (uint);
    function getFunderRefunded(uint jobId, address user) external view returns (bool);
    function getFunderQuantity(uint jobId, address funder) external view returns (uint);
    function getFunderQuantities(uint jobId) external view returns (address[] memory, uint[] memory);
    function getFunderQuantityAt(uint jobId, uint index) external view returns (address, uint);
    function getNumFunderQuantities(uint jobId) external view returns (uint);
    function getApplicantTimes(uint jobId) external view returns (address[] memory, uint[] memory);
    function getApplicantTimesAt(uint jobId, uint index) external view returns (address, uint);
    function getNumApplicants(uint jobId) external view returns (uint);
    function hasApplied(address user, uint jobId) external view returns (bool);
    function getAppliedTimes(address user) external view returns (uint[] memory, uint[] memory);
    function getAppliedTimesAt(address user, uint index) external view returns (uint, uint);
    function getNumAppliedTimes(address user) external view returns (uint);
    function hasFunded(address user, uint jobId) external view returns (bool);
    function getFundedTimes(address user) external view returns (uint[] memory, uint[] memory);
    function getFundedTimesAt(address user, uint index) external view returns (uint, uint);
    function getNumFundedTimes(address user) external view returns (uint);
    function getManaged(address user) external view returns (uint[] memory);
    function getManagedAt(address user, uint index) external view returns (uint);
    function getNumManaged(address user) external view returns (uint);
    function getWorked(address user) external view returns (uint[] memory);
    function getWorkedAt(address user, uint index) external view returns (uint);
    function getNumWorked(address user) external view returns (uint);
    function getOpen() external view returns (uint[] memory);
    function getOpenAt(uint index) external view returns (uint);
    function getNumOpen() external view returns (uint);
    function getFilled() external view returns (uint[] memory);
    function getFilledAt(uint index) external view returns (uint);
    function getNumFilled() external view returns (uint);
    function getCancelled() external view returns (uint[] memory);
    function getCancelledAt(uint index) external view returns (uint);
    function getNumCancelled() external view returns (uint);
    function getOpen(address token) external view returns (uint[] memory);
    function getOpenAt(address token, uint index) external view returns (uint);
    function getNumOpen(address token) external view returns (uint);
    function getFilled(address token) external view returns (uint[] memory);
    function getFilledAt(address token, uint index) external view returns (uint);
    function getNumFilled(address token) external view returns (uint);
    function getCancelled(address token) external view returns (uint[] memory);
    function getCancelledAt(address token, uint index) external view returns (uint);
    function getNumCancelled(address token) external view returns (uint);
    function getTokens() external view returns (address[] memory);
    function getTokenAt(uint index) external view returns (address);
    function getNumTokens() external view returns (uint);
}
